common/xfs: Add a helper to get an inode fork's extent count
This commit adds the helper _scratch_get_inode_extcnt() which returns an
inode's extent count.

Signed-off-by: Chandan Babu R <chandanrlinux@gmail.com>

diff --git a/common/xfs b/common/xfs
--- a/common/xfs
+++ b/common/xfs
@@ -883,6 +883,29 @@ _scratch_get_bmx_prefix() {
 	return 1
 }
 
+_scratch_get_inode_extcnt()
+{
+	ino=$1
+	whichfork=$2
+
+	case $whichfork in
+		"attr")
+			field=core.naextents
+			;;
+		"data")
+			field=core.nextents
+			;;
+		*)
+			echo "Invalid fork"
+			exit 1
+	esac
+
+	nextents=$(_scratch_xfs_db  -c "inode $ino" -c "print $field")
+	nextents=${nextents##${field} = }
+
+	echo $nextents
+}
+
 #
 # Ensures that we don't pass any mount options incompatible with XFS v4
 #
